name: Caching Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Restore benchmark result
      uses: actions/cache/restore@v3
      with:
        path: benchmark-result
        key: benchmark-result
    - name: Benchmark
      run: |
        mkdir benchmark-result
        date > benchmark-result/test.md
        echo "22222222" >> benchmark-result/test.md
    - name: test
      run: |
        sudo apt install tree
        tree . -L 2
        cat benchmark-result/test.md
    - name: Save Benchmark Result
      uses: actions/cache/save@v3
      with:
        path: benchmark-result
        key: benchmark-result
