name: Caching Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache benchmark
      id: benchmark-cache
      uses: actions/cache@v3
      with:
        path: benchmark-result
        key: benchmark-result
    - name: Cache False
      if: steps.cache-benchmark.outputs.cache-hit != 'true'
      run: |
        echo "## test" > test.md
    - name: test
      run: |
        sudo apt install tree
        tree . -L 2
        cat *.md
    - name: Save Benchmark Result
      id: benchmark-save
      uses: actions/cache/save@v3
      with:
        path: |
          test.md
        key: ${{ steps.benchmark-cache.outputs.cache-primary-key }}