name: Caching Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache benchmark
      id: benchmark-cache
      uses: actions/cache@v3
      with:
        path: benchmark-result
        key: benchmark-result
    - name: Cache False
      if: steps.benchmark-cache.outputs.cache-hit == 'false'
      run: |
        echo "## test_false" >> benchmark-result/test.md
    - name: Cache True
      if: steps.benchmark-cache.outputs.cache-hit == 'true'
      run: |
        echo "## sucess_true" >> benchmark-result/test.md
    - name: Bench
      run: |
        date >> benchmark-result/test.md
    - name: test
      run: |
        sudo apt install tree
        tree . -L 2
        cat benchmark-result/test.md
    - name: Save Benchmark Result
      id: benchmark-save
      uses: actions/cache/save@v3
      with:
        path: benchmark-result
        key: benchmark-result
