name: Caching Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Restore benchmark result
      uses: actions/cache@v3
      id: benchmark-cache
      with:
        path: benchmark-result-pre
        key: benchmark-result
    - name: Benchmark
      if: steps.benchmark-cache.outputs.cache-hit == 'false'
      run: |
        date >> benchmark-result-pre/test.md
        echo "false" >> benchmark-result-pre/test.md
    - name: Benchmark
      if: steps.benchmark-cache.outputs.cache-hit == 'true'
      run: |
        date >> benchmark-result-pre/test.md
        echo "true" >> benchmark-result-pre/test.md
    - name: test
      run: |
        sudo apt install tree
        tree . -L 2
        cat benchmark-result-pre/test.md
    - name: Save Benchmark Result
      uses: actions/cache/save@v3
      with:
        path: benchmark-result-pre
        key: benchmark-result
