name: Caching Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Restore benchmark result
      uses: actions/cache/restore@v3
      with:
        path: benchmark-result-pre
        key: benchmark-result
    - name: Benchmark
      run: |
        if [ ! -d "benchmark-result-pre" ]; then
          mkdir -p "benchmark-result-pre"
        fi
        date >> benchmark-result-pre/test.md
        install -D benchmark-result-pre/test.md benchmark-result/test.md
        cat benchmark-result/test.md
        sudo apt install update && apt install tree
        tree . -L 2
    - name: Save Benchmark Result
      uses: actions/cache/save@v3
      with:
        path: benchmark-result
        key: benchmark-result
