name: Caching Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Restore benchmark result
      id: benchmark-cache-restore
      uses: actions/cache@v3
      with:
        path: benchmark-result
        key: benchmark-result
    - name: Benchmark
      run: |
        if [ ! -d "benchmark-result" ]; then
          mkdir -p "benchmark-result"
        fi
        tree . -L 2
        date >> benchmark-result/test.md
        cat benchmark-result/test.md
    - name: Save Benchmark Result
      uses: actions/cache/save@v3
      with:
        path: benchmark-result
        key: ${{ steps.benchmark-cache-restore.outputs.cache-matched-key }}
