name: Error Test

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: "main"
      - name: Test application
        run: |
          echo "::error title={benchmark-result}::warning"
