name: Error Test

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: "main"
      - name: Test application
        run: |
          echo "Error PR" >&2 && exit 1
