name: Error Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: "main"
      - uses: Desiki-high/action/.github/workflows/reuse.yml
      - name: Test application
        run: |
          echo "::error title={benchmark-result}::warning" && exit 1
