name: Error Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: "main"
      - name: reuse
        uses: .github/workflows/reuse.yml@main
      - name: Test application
        run: |
          echo "::error title={benchmark-result}::warning" && exit 1
