name: Thank you for your pull request

on:
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Comment on pull request
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: Thanks for your contribution!
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}