on: pull_request_target

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: test
        id: result
        run: |
          date > test.md
      - uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const markdownFilePath = 'test.md';
            const markdownContent = fs.readFileSync(markdownFilePath, 'utf8');

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: markdownContent,
            });
