name: test

permissions:
  pull-requests: write

on:
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Read Markdown file
        id: markdown
        run: |
          echo "| bench-result | pull-elapsed(s) | create-elapsed(s) | run-elapsed(s) | total-elapsed(s) |" > result.md
          echo "::set-output name=content::$(cat result.md)"
      - name: Add comment to Pull Request
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const markdown = '${{ steps.markdown.outputs.content }}';
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: markdown
            })
      - name: test
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            Release ${{ github.sha }} to <https://pr-${{ github.event.number }}.example.com>
