name: PR Comment

on: push

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: test
        id: result
        run: |
          echo "Action started at ${{ github.event.created_at }}"